server:
  port: 9990
  servlet:
    context path: "/user/mgmt"

spring:
  application:
    name: user
  mvc:
    path match:
      matching-strategy: ant-path-matcher
#config:
#  rest:
#    service:
#      encryptionKey: "keycodevalue"

#app:
#  name: spring boot application
#  api:
#    title: Spring Boot APIs
#    version: 1.0.0
#    description: Spring Boot APIs description
#    base-package: com.example.demo.DemoApplication
#    contact-name: apisupportgroup
#    contact-email: apisupportgroup@abc.com
#    swagger:
#      enable: true