server:
  port: 9990
  servlet:
    context path: "/user/mgmt"

spring:
  application:
    name: user
  mvc:
    path match:
      matching-strategy: ant-path-matcher

  data:
    mongodb:
      user: admin
      password: admin
      database: bus-booking-system
      uri: mongodb://localhost:27017
#config:
#  rest:
#    service:
#      encryptionKey: "keycodevalue"

